### ISSUE TITLE
Application to Execute does not Exist

### ISSUE THREAD

**Issue by GhoulTsu** [ronelm2000/wsmtools#16] opened 2020-09-04 19:37 UTC
I am unable to export on v.0.4.0. I receive an error which states that the application at 'C:\Users\Name\AppData\Local\Temp\.net\wstools\vof4n0tx.fio\wstools.dll' does not exist.

**Comment by ronelm2000** [comment] 2020-09-21 05:41
This may occur if you delete Temporary Files as you open wstools. I cannot reproduce this error otherwise. The only advise I can give is delete all temporary files in full, then try again.

**Comment by ronelm2000** [comment] 2020-12-04 05:17
Official Fix has been filed for #24

**Closed by ronelm2000** 2020-12-04 05:17 UTC
