### ISSUE TITLE
Image Low quality

### ISSUE THREAD

**Issue by Slss0106** [ronelm2000/wsmtools#39] opened 2021-03-31 10:05 UTC
The quality of the image exported is extremely low to the point even the power is almost unreadable. 
![deck_mirimu](https://user-images.githubusercontent.com/74620064/113127732-abf38d80-924b-11eb-85ef-69ab39519152.jpg)

**Comment by ronelm2000** [comment] 2021-03-31 10:37
That would have been resolved by using DeckLog images; can you try deleting the cards.db first and trying again, then posting a text file of the output so that I can help?

**Comment by Slss0106** [comment] 2021-03-31 12:16
What do you mean by decklog images? and how do I find the text file of the output? I did try and delete the card.db but the result is still the same

**Comment by Slss0106** [comment] 2021-03-31 12:29
suing decklog images gives me this:
![Screenshot_1](https://user-images.githubusercontent.com/74620064/113144269-a3a54d80-925f-11eb-85a4-0bd589af2547.png)

**Comment by ronelm2000** [comment] 2021-03-31 13:24
> What do you mean by decklog images?
The source of the images meaning where it's sourced.
> and how do I find the text file of the output?
Just copy/paste the entire output to notepad. You can select text by doing the following:
1. Right-clicking on the PowerShell terminal.
2. Select Edit > Select All
![image](https://user-images.githubusercontent.com/12634987/113150453-ad7e7f00-9266-11eb-9d94-7caa2e1c6e71.png)
3. Everything should be highlighted. Press Enter to copy everything to Clipboard.
![image](https://user-images.githubusercontent.com/12634987/113150600-d4d54c00-9266-11eb-9de7-07f24cf17682.png)
4. Paste it to Notepad, then attach it on this issue.

PS: If you're trying to use a DeckLog link, you'll need to manually source a set link, and parse it, like so:
```ps
# This command gets cards from Slime vol. 1.
./wstools parse https://www.encoredecks.com/?page=1&set=5df3d074202372df5e727c5f
```

**Comment by ronelm2000** [comment] 2021-03-31 13:27
That being said, I found the cause:
```ps
[21:25:27 INF] [Montage.Weiss.Tools.Impls.Parsers.Cards.EncoreDecksParser] Compatibility Passed for: "https://www.encoredecks.com/?page=1&set=5df3d074202372df5e727c5f"
[21:25:27 INF] [Montage.Weiss.Tools.Impls.Parsers.Cards.EncoreDecksParser] Converting URL into API link...
[21:25:35 WRN] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] DeckLog's API has been updated from "20210309.001" to "20210329.002".
[21:25:35 WRN] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Please check with the developer for a newer version that ensures compatibility with the newest version.
[21:25:35 INF] [Montage.Weiss.Tools.Impls.PostProcessors.DeckLogPostProcessor] Skipping.
```

I'm going to post a new version which ensures compatibility with the latest DeckLog API.

**Comment by Slss0106** [comment] 2021-03-31 13:35
here is the output text for both when using decklog and encore.
[output text encore.txt](https://github.com/ronelm2000/wsmtools/files/6236936/output.text.encore.txt)

**Closed** 2021-03-31 13:52 UTC
Labels: bug

**Comment by ronelm2000** [comment] 2021-03-31 18:21
Unless EncoreDecks makes foil info available on their website, it's highly unlikely. For that use case, parse the card set using HOTC.
